import threading
import cv2
import base64
from groq import Groq
from utils.logger import log
from utils.config_loader import get_env

client = Groq(api_key=get_env("GROQ_API_KEY"))
MODEL  = "meta-llama/llama-4-scout-17b-16e-instruct"

_validation_results = {}
_pending            = set()


def _frame_to_base64(frame) -> str:
    _, buffer = cv2.imencode(".jpg", frame)
    return base64.b64encode(buffer).decode("utf-8")


def _build_prompt(worker_id: str, angles: dict) -> str:
    neck = angles.get("neck", "N/A")
    back = angles.get("back", "N/A")
    knee = angles.get("knee", "N/A")

    return f"""You are a senior occupational safety and ergonomics assessor for construction and industrial environments.
You are given:
1. A camera image of a worker.
2. Estimated body-joint angles derived from pose estimation.
3. A preliminary HIGH-RISK flag generated by an automated posture scoring system.

Your job is to VERIFY whether the automated alert is a genuine safety concern or a false positive.

IMPORTANT CONTEXT
Construction workers routinely perform tasks that involve:
* Kneeling, Squatting, Sitting on the ground
* Working at floor level, Leaning forward
* Reaching overhead, Temporary crouched positions
These activities are often normal and should NOT automatically be considered dangerous.
Your decision must prioritize visual evidence from the image over the numerical risk score.

Worker Information
Worker ID: {worker_id}
Pose Angles:
* Neck Angle: {neck}°
* Back/Trunk Angle: {back}°
* Knee Angle: {knee}°

Evaluation Criteria
STEP 1 – Visual Verification
* Is the worker stable and balanced?
* Does the posture appear intentional and task-related?
* Is the worker kneeling, crouching, or sitting in a controlled manner?

STEP 2 – Ergonomic Risk Assessment
* Extreme trunk flexion, severe neck bending, awkward twisting
* Loss of balance, potential fall risk, signs of collapse or injury

STEP 3 – False Positive Filtering
Treat as NORMAL if posture appears task-related and stable.
Treat as DANGEROUS only if image clearly shows unsafe posture with obvious ergonomic strain.

Decision Rule: If uncertain, choose NORMAL.
Output exactly one word — DANGEROUS or NORMAL. No explanations."""


def validate_async(angles: dict, worker_id: str, frame=None):
    if worker_id in _pending:
        return

    frame_copy = frame.copy() if frame is not None else None

    def _run():
        _pending.add(worker_id)
        try:
            prompt = _build_prompt(worker_id, angles)

            if frame_copy is not None:
                b64      = _frame_to_base64(frame_copy)
                messages = [
                    {
                        "role": "user",
                        "content": [
                            {"type": "text",      "text": prompt},
                            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}}
                        ]
                    }
                ]
            else:
                messages = [{"role": "user", "content": prompt}]

            response = client.chat.completions.create(
                model      = MODEL,
                messages   = messages,
                max_tokens = 5,
            )

            result = response.choices[0].message.content.strip().upper()

            if result not in ("DANGEROUS", "NORMAL"):
                log.warning(f"Unexpected Groq response: '{result}' — defaulting NORMAL")
                result = "NORMAL"

            _validation_results[worker_id] = (result == "DANGEROUS")
            log.debug(f"Groq posture [{worker_id}]: {result}")

        except Exception as e:
            log.warning(f"Groq validation failed: {e} — using rule-based fallback")
            _validation_results[worker_id] = True
        finally:
            _pending.discard(worker_id)

    threading.Thread(target=_run, daemon=True).start()


def get_validation_result(worker_id: str) -> bool:
    return _validation_results.get(worker_id, True)